#!/bin/sh

device=/dev/sdd
partition=1
target=$device$partition

abort() {
	echo "aborted: $@"
	exit 1
}

if [ $(whoami) != root ]; then
	echo "use sudo Luke!"
	exit 1
fi

echo "setting bootable flag"
parted $device set $partition boot on || abort "can't set bootable flag"

echo "writng MBR"
dd bs=440 conv=notrunc count=1 if=/usr/share/syslinux/mbr.bin of=$target || abort "dd failed"
echo "creating fs"
mkfs.vfat -n FX_LIVE $target || abort "can't create filesystem"

echo "installing bootloader"
syslinux $target || abort "syslinux failed"

